language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

# before_script:
# - npm install -g gulp

script:
  - hexo g 

# after_script:

branches:
  only:
    - source

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: public
  target-branch: master
  on:
    branch: source
